name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck web
        run: npx tsc --noEmit -p .
        working-directory: apps/web

      - name: Typecheck api
        run: npx tsc --noEmit -p .
        working-directory: apps/api
